grafana:
  build: grafana/
  expose:
   - "3000"
  volumes:
   - ~/.btcdmon/var/log/grafana:/var/log/grafana
   - ~/.btcdmon/var/lib/grafana:/var/lib/grafana
influxdb:
  build: influxdb/
  ports:
   - "8086:8086"
  expose:
   - "8083"
  volumes:
   - ~/.btcdmon/data:/data
nginx:
  build: nginx/
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ~/.btcdmon/var/log/nginx:/var/log/nginx
  links:
   - grafana
   - influxdb
